### ISSUE TITLE
make fails with Eigen/Dense: No such file or directory

### ISSUE THREAD

**Issue by cyian-1756** [stelic/limitload#8]
Trying to build on ubuntu 16.04 running makes fails with `/usr/include/panda3d/lsimpleMatrix.h:21:23: fatal error: Eigen/Dense: No such file or directory`

This is even after I install `libeigen3-dev`

**Comment by nikolmiv** [comment]
Oops, that was fix for another issue.

**Comment by nikolmiv** [comment]
Oh, have you got Panda built with support for Eigen? IIRC, before we removed this from our builds, it was necessary to add include directive for Eigen headers into compiler options. How about if you add:

  -I /usr/include/eigen3

next to other includes in util/build_module.sh line 53? If it works, I'll try and add it in some slightly nicer way.

**Comment by cyian-1756** [comment]
That seems to have fixed the first issue, but now make errors out with ```error: cannot use typeid with -fno-rtti
   string base_name = typeid(Base).name();```

Edit: This was fixed by editing build_setup

**Comment by cyian-1756** [comment]
Adding `-I /usr/include/eigen3` fixed the build
